allowBuilds:
  - esbuild
  - lightningcss

onlyBuiltDependencies:
  - esbuild
  - lightningcss

minimumReleaseAge: 4320

blockExoticSubdeps: true

trustPolicy: "no-downgrade"

strictDepBuilds: true

ignoreScripts: true

trustPolicyExclude:
  - "@trickfilm400/rollup-plugin-off-main-thread"
  - semver
  - undici-types